apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sshd
  labels:
    app: sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
      - name: sshd
        image: docker.io/tnozicka/sshd
        ports:
        - containerPort: 2222
        - containerPort: 5000
