kind: Service
apiVersion: v1
metadata:
  name: acme-controller
spec:
  selector:
    app: sshd
  ports:
  - name: ssh
    protocol: TCP 
    port: 2222
    targetPort: 2222
  - name: http
    protocol: TCP 
    port: 80
    targetPort: 5000

